apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
    name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        name: result-app-pod
        app: demo-voting-app
  template:
    metadata:
        name: result-app-pod
        labels:
            name: result-app-pod
            app: demo-voting-app
    spec:
        containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
          - containerPort: 80
